# Generated by Django 4.2.2 on 2024-04-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
