# Generated by Django 4.2.2 on 2024-04-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_medicalrecord_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='description',
            new_name='diagnosis',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prescribed_medication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
