# Generated by Django 4.2.2 on 2024-04-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_medicalrecord_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
